### ISSUE TITLE
rotintro.mp3 missing

### ISSUE THREAD

**Issue by kittybwained** [skadakar/garble#2]
Whenever i try to make an ROT message, it gives me this error:
`Traceback (most recent call last):
  File "C:\Users\4tlas\Downloads\garble\garble.py", line 388, in <module>
    send_rot_message(sys.argv[2], sys.argv[4], sys.argv[6])
  File "C:\Users\4tlas\Downloads\garble\garble.py", line 337, in send_rot_message
    play("audio", "rotintro")
  File "C:\Users\4tlas\Downloads\garble\garble.py", line 85, in play
    AudioPlayer(soundfullpath).play(block=True)
  File "C:\Users\4tlas\AppData\Local\Programs\Python\Python310\lib\site-packages\audioplayer\audioplayer_windows.py", line 7, in __init__
    super().__init__(filename)
  File "C:\Users\4tlas\AppData\Local\Programs\Python\Python310\lib\site-packages\audioplayer\abstractaudioplayer.py", line 31, in __init__
    raise FileNotFoundError(
FileNotFoundError: File does not exist: "C:\Users\4tlas\Downloads\garble\audio\rotintro.mp3"`

**Comment by skadakar** [comment]
ROT was added later in the project so it was forgotten.. if you find something suitable make a PR, not a priority atm.
